version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.0-ce-git
    working_directory: ~/my_app
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          pip install awscli;
          TAG=293713961925.dkr.ecr.us-west-1.amazonaws.com/nginx:latest;
          docker build -t $TAG .;
          aws ecr get-login --no-include-email --region us-west-1;
          docker push $TAG
