version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/my_app
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          docker build .;
          docker run -d -p 80:80 --name nginx-test nginx:alpine; sleep 10
          
# machine:
#   services:
#     - docker

# dependencies:
#   post:
#     - docker build .

# test:
#   post:
#     - docker run -d -p 80:80 --name nginx-test nginx:alpine; sleep 10
#     - curl --retry 10 --retry-delay 5 localhost:8080 | grep "nginx!"

# deployment:
#   prod:
#     branch: master
#     commands:
#       - ./deploy.sh
