version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/my_app
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          sudo apt-get install awscli
          
          docker build -t 293713961925.dkr.ecr.us-west-1.amazonaws.com/nginx:latest .;
          aws ecr get-login --no-include-email --region us-west-1;
          docker push 293713961925.dkr.ecr.us-west-1.amazonaws.com/nginx:latest
